name: Go Build and Release Executables

on:
  push:
    branches: 
      - "main"
      - "bedrock"

    paths:
      - "version"


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.23.3'

    - name: Install dependencies
      run: go mod tidy

    - name: Build Windows executable
      run: |
        GOOS=windows GOARCH=amd64 go build -v -o Eulogist-main-windows-x86_64.exe

    - name: Provide release version
      id: release_version
      run: |
        VERSION=$(cat version)
        echo "release_version=$VERSION" >> $GITHUB_ENV
        echo "::set-output name=release_version::$VERSION"

    - name: Build Termux executables
      run: |
        git fetch origin bedrock
        git checkout bedrock
        git pull origin bedrock
        GOOS=android GOARCH=arm GOARM=7 go build -v -o Eulogist-bedrock-termux-armv7
        GOOS=android GOARCH=arm64 go build -v -o Eulogist-bedrock-termux-arm64
        GOOS=android GOARCH=amd64 go build -v -o Eulogist-bedrock-termux-x86_64
        GOOS=android GOARCH=386 go build -v -o Eulogist-bedrock-termux-x86

    - name: Upload executables to GitHub Release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          Eulogist-main-windows-x86_64.exe
          Eulogist-bedrock-termux-armv7
          Eulogist-bedrock-termux-arm64
          Eulogist-bedrock-termux-x86_64
          Eulogist-bedrock-termux-x86
        tag_name: v${{ steps.release_version.outputs.release_version }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
